apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-deployment
spec:
  replicas: 2  # Number of desired replicas
  selector:
    matchLabels:
      app: box-game
  template:
    metadata:
      labels:
        app: box-game
    spec:
      containers:
      - name: box-game
        image: yash5090/box-game:latest
        ports:
        - containerPort: 5000
