apiVersion: apps/v1
kind: Deployment
metadata:
  name: box-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: box-game
  template:
    metadata:
      labels:
        app: box-game
    spec:
      containers:
        - name: box-game
          image: yash5090/box-game:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
